import { IJobPosition } from "types/experience";
import { Stack } from "../stack";

export const EXPERIENCE: IJobPosition[] = [
  {
    title: "Founder & CTO",
    date: "Mar 2023 - Nov 2023",
    company: "MeetMap",
    description: [
      "Led the design and development of real-time location mobile application.",
      "Designed scalable and robust event-driven infrastructure for 10,000 concurrent users and more using AWS, ECS Fargate, Terraform, NestJS and RabbitMQ.",
      "Created recommendation engine using Opensearch.",
      "Created highly scalable static assets processing service (videos, photos, etc).",
      "App introduction and making connections on different meetups and conferences.",
      "Mobile app development using React Native (Bare flow).",
    ],
    place: "Tel Aviv",
    stack: [
      Stack.TYPESCRIPT,
      Stack.GIT,
      Stack.HTML,
      Stack.CSS,
      Stack.SASS,
      Stack.JS,
      Stack.STYLED_COMPONENTS,
      Stack.FRAMER_MOTION,
      Stack.REACT,
      Stack.NEXTJS,
      Stack.WEBPACK,
      Stack.BABEL,
      Stack.NODEJS,
      Stack.NESTJS,
      Stack.MySQL,
      Stack.REST,
      Stack.SWAGGER,
      Stack.DOCKER,
      Stack.AWS,
      Stack.TERRAFORM,
      Stack.MICROSERVICES,
    ],
  },
  {
    title: "Full-Stack Developer",
    date: "Jan 2023 - Current",
    company: "Alsomine",
    description: [
      "Leading the development of promocodes as NFT marketplace using the latest technologies of Next.js, NestJS, Terraform, Prisma, Postgres, Redis, Solidity and Ethers.js.",
      "E2E testing with Playwright, Jest unit testing, Artillery performance testing.",
      "Robust integration with third-party APIs.",
      "Designing and creation of NFT marketplace with secured sensitive-metadata NFTs.",
    ],
    place: "Tel Aviv",
    stack: [
      Stack.TYPESCRIPT,
      Stack.GIT,
      Stack.HTML,
      Stack.CSS,
      Stack.SASS,
      Stack.JS,
      Stack.STYLED_COMPONENTS,
      Stack.FRAMER_MOTION,
      Stack.REACT,
      Stack.NEXTJS,
      Stack.WEBPACK,
      Stack.BABEL,
      Stack.NODEJS,
      Stack.NESTJS,
      Stack.MySQL,
      Stack.REST,
      Stack.SWAGGER,
      Stack.DOCKER,
      Stack.AWS,
      Stack.TERRAFORM,
    ],
  },
  {
    title: "Full-Stack Developer & Founding Technical member",
    date: "Sep 2022 - Jan 2023",
    company: "Othentic",
    description: [
      "Developed a robust architecture with NestJS, gRPC, Protobuf, .NET 7 that handled 300 data read/write operations per second via RabbitMQ, receiving data from external API via websockets (Opensea API).",
      "Developed a complex dashboard with React, dagre, recharts, reactflow.",
      "Developed an intuitive frontend interface with React, dagre, reactflow allowing users to create, view and edit complex logical expressions using drag-and-drop. In addition users can auto-format their flows for better visual clarity of the logical diagrams.",
    ],
    place: "Tel Aviv",
    stack: [
      Stack.TYPESCRIPT,
      Stack.GIT,
      Stack.JIRA,
      Stack.HTML,
      Stack.CSS,
      Stack.SASS,
      Stack.JS,
      Stack.STYLED_COMPONENTS,
      Stack.FRAMER_MOTION,
      Stack.REACT,
      Stack.REDUX,
      Stack.WEBPACK,
      Stack.BABEL,
      Stack.NODEJS,
      Stack.NESTJS,
      Stack.MySQL,
      Stack.REST,
      Stack.WEBAPI,
      Stack.CSHARP,
      Stack.DOTNET,
      Stack.SWAGGER,
      Stack.RABBIT_MQ,
      Stack.GRPC,
      Stack.PROTO,
      Stack.MICROSERVICES,
      Stack.DOCKER,
      Stack.TRUFFLE,
      Stack.GANACHE,
      Stack.SOLIDITY,
      Stack.HARDHAT,
    ],
  },
  {
    title: "Blockchain Engineer, Contract",
    date: "Sep 2022 - Nov 2022",
    company: "Get-In",
    description: [
      "Designed and developed Tickets as Nft microservice.",
      "Designed and developed smart contracts using Solidity and ECDSA mint functionality.",
      "Led the integration with the existing system.",
    ],
    place: "Tel Aviv",
    stack: [
      Stack.TYPESCRIPT,
      Stack.GIT,
      Stack.JIRA,
      Stack.NODEJS,
      Stack.NESTJS,
      Stack.MySQL,
      Stack.REST,
      Stack.SWAGGER,
      Stack.JENKINS,
      Stack.RABBIT_MQ,
      Stack.GRPC,
      Stack.PROTO,
      Stack.MICROSERVICES,
      Stack.DOCKER,
      Stack.TRUFFLE,
      Stack.GANACHE,
      Stack.SOLIDITY,
      Stack.HARDHAT,
    ],
  },
  {
    title: "Full-Stack Developer",
    date: "Jan 2022 - Sep 2022",
    company: "Zira1",
    description: [
      "Led performance improvement for the GraphQL API, optimized MongoDB aggregations and optimized Strapi v3 plugins, which reduced API latency up to 80%.",
    ],
    place: "Herzliya, Israel",
    stack: [
      Stack.GIT,
      Stack.JIRA,
      Stack.HTML,
      Stack.CSS,
      Stack.SASS,
      Stack.JS,
      Stack.STYLED_COMPONENTS,
      Stack.NEXTJS,
      Stack.NODEJS,
      Stack.EXPRESS,
      Stack.MONGO,
      Stack.REDIS,
      Stack.GRAPH,
      Stack.STRAPI,
    ],
  },
  {
    title: "Full-Stack Developer",
    date: "Jan 2022 - Current",
    company: "Freelance",
    description: [
      "Desperate Ape Wives, Dapps development (backend, frontend, smart contracts).",
      "Save The Date, Dapp development, backend and frontend, merkle proof.",
      "Other projects, Dapp development, backend, frontend, smart contract with ECDSA mint functionality.",
    ],
    place: "Tel Aviv",
    stack: [
      Stack.TYPESCRIPT,
      Stack.GIT,
      Stack.HTML,
      Stack.CSS,
      Stack.SASS,
      Stack.JS,
      Stack.STYLED_COMPONENTS,
      Stack.FRAMER_MOTION,
      Stack.REACT,
      Stack.REDUX,
      Stack.WEBPACK,
      Stack.BABEL,
      Stack.NODEJS,
      Stack.EXPRESS,
      Stack.NESTJS,
      Stack.MONGO,
      Stack.REST,
      Stack.DOCKER,
      Stack.TRUFFLE,
      Stack.GANACHE,
      Stack.SOLIDITY,
      Stack.HARDHAT,
    ],
  },
  {
    title: "Full-Stack Developer",
    date: "Jan 2019 - Dec 2021",
    company: "Terexov",
    description: ["Worked as a Full-Stack developer on different projects in a digital agency."],
    place: "Saint Petersburg",
    stack: [
      Stack.TYPESCRIPT,
      Stack.GIT,
      Stack.JIRA,
      Stack.HTML,
      Stack.CSS,
      Stack.SASS,
      Stack.JS,
      Stack.STYLED_COMPONENTS,
      Stack.FRAMER_MOTION,
      Stack.REACT,
      Stack.REDUX,
      Stack.WEBPACK,
      Stack.BABEL,
      Stack.NODEJS,
      Stack.EXPRESS,
      Stack.MONGO,
      Stack.REST,
    ],
  },
];
