import { IJobPosition } from "types/experience";
import { Stack } from "../stack";

export const EXPERIENCE: IJobPosition[] = [
  {
    title: "Blockchain full stack engineer",
    date: "2022",
    company: "Othentic",
    description: [
      "Building complex dashboard, using react from a scratch",
      "React project configuration with webpack and babel",
      "Building scalable microservice architecture, using .NET 7 and WebAPI, modern queues such as RabbitMQ",
      "Frontend optimisation",
      "Blockchain integration",
      "Opensea api integration",
      "Data visualisation (graphics, flow, etc)",
    ],
    place: "Tel Aviv",
    stack: [
      Stack.TYPESCRIPT,
      Stack.GIT,
      Stack.JIRA,
      Stack.HTML,
      Stack.CSS,
      Stack.SASS,
      Stack.JS,
      Stack.STYLED_COMPONENTS,
      Stack.FRAMER_MOTION,
      Stack.REACT,
      Stack.REDUX,
      Stack.WEBPACK,
      Stack.BABEL,
      Stack.NODEJS,
      Stack.NESTJS,
      Stack.MySQL,
      Stack.REST,
      Stack.WEBAPI,
      Stack.CSHARP,
      Stack.DOTNET,
      Stack.SWAGGER,
      Stack.RABBIT_MQ,
      Stack.GRPC,
      Stack.PROTO,
      Stack.MICROSERVICES,
      Stack.DOCKER,
      Stack.TRUFFLE,
      Stack.GANACHE,
      Stack.SOLIDITY,
      Stack.HARDHAT,
    ],
  },
  {
    title: "Blockchain full stack engineer",
    date: "2022",
    company: "Several Web3 Projects",
    description: [
      "Building simple react websites from a scratch",
      "React project configuration with webpack and babel",
      "Web3 integration",
      "Building simple backends with NestJS",
      "Creating simple an complex smartcontracts, requiring knowledge in cryptographic signatures",
    ],
    place: "Tel Aviv",
    stack: [
      Stack.TYPESCRIPT,
      Stack.GIT,
      Stack.HTML,
      Stack.CSS,
      Stack.SASS,
      Stack.JS,
      Stack.STYLED_COMPONENTS,
      Stack.FRAMER_MOTION,
      Stack.REACT,
      Stack.NEXTJS,
      Stack.REDUX,
      Stack.WEBPACK,
      Stack.BABEL,
      Stack.NODEJS,
      Stack.EXPRESS,
      Stack.NESTJS,
      Stack.MONGO,
      Stack.REST,
      Stack.DOCKER,
      Stack.TRUFFLE,
      Stack.GANACHE,
      Stack.SOLIDITY,
      Stack.HARDHAT,
    ],
  },
  {
    title: "Backend engineer",
    date: "Sep – Nov 2022",
    company: "Get-In",
    description: [
      "Backend optimisation",
      "Nft integration to ticketing system",
      "Web3 integration",
      "Creating protbuf files",
      "Creating docker files",
      "Building microservices architecture with NestJS, RabbitMQ and GRpc",
      "Creating upgradable smartcontract, required knowledge in cryptographic signatures",
    ],
    place: "Tel Aviv",
    stack: [
      Stack.TYPESCRIPT,
      Stack.GIT,
      Stack.JIRA,
      Stack.NODEJS,
      Stack.NESTJS,
      Stack.MySQL,
      Stack.REST,
      Stack.SWAGGER,
      Stack.JENKINS,
      Stack.RABBIT_MQ,
      Stack.GRPC,
      Stack.PROTO,
      Stack.MICROSERVICES,
      Stack.DOCKER,
      Stack.TRUFFLE,
      Stack.GANACHE,
      Stack.SOLIDITY,
      Stack.HARDHAT,
    ],
  },
  {
    title: "Full Stack Engineer (freelance)",
    date: "2022",
    company: "Save The Date (STD)",
    description: [
      "Building react website from a scratch",
      "React project configuration with webpack and babel",
      "Web3 integration",
      "Building simple backend with ExpressJS and MongoDB and Service workers",
      "Creating simple an complex smartcontracts, requiring knowledge in cryptographic signatures",
    ],
    place: "Tel Aviv",
    stack: [
      Stack.TYPESCRIPT,
      Stack.GIT,
      Stack.HTML,
      Stack.CSS,
      Stack.SASS,
      Stack.JS,
      Stack.STYLED_COMPONENTS,
      Stack.FRAMER_MOTION,
      Stack.REACT,
      Stack.WEBPACK,
      Stack.BABEL,
      Stack.NODEJS,
      Stack.EXPRESS,
      Stack.MONGO,
      Stack.REST,
      Stack.SOLIDITY,
      Stack.HARDHAT,
    ],
  },
  {
    title: "Full Stack Engineer",
    date: "June – Oct 2022",
    company: "Zira1 (big real estate agency)",
    description: [
      "Backend optimisation",
      "Frontend optimisation",
      "Database queries optimisation",
      "CRM optimisation",
      "Redis cache optimisation",
      "Working with Strapi CRM and Graphql server",
    ],
    place: "Tel Aviv",
    stack: [
      Stack.GIT,
      Stack.JIRA,
      Stack.HTML,
      Stack.CSS,
      Stack.SASS,
      Stack.JS,
      Stack.STYLED_COMPONENTS,
      Stack.NEXTJS,
      Stack.NODEJS,
      Stack.EXPRESS,
      Stack.MONGO,
      Stack.REDIS,
      Stack.GRAPH,
      Stack.STRAPI,
    ],
  },
  {
    title: "Full Stack Engineer (freelance)",
    date: "2022",
    company: "Desperate Ape Wives (DAW)",
    description: [
      "Building react websites from a scratch",
      "React projects configuration with webpack and babel",
      "Web3 integration",
      "Backend and frontend deployment",
      "Building simple backends with NestJS",
      "Creating simple an complex smartcontracts, requiring knowledge in cryptographic signatures",
    ],
    place: "Tel Aviv",
    stack: [
      Stack.TYPESCRIPT,
      Stack.GIT,
      Stack.HTML,
      Stack.CSS,
      Stack.SASS,
      Stack.JS,
      Stack.STYLED_COMPONENTS,
      Stack.FRAMER_MOTION,
      Stack.REACT,
      Stack.REDUX,
      Stack.WEBPACK,
      Stack.BABEL,
      Stack.NODEJS,
      Stack.EXPRESS,
      Stack.NESTJS,
      Stack.MONGO,
      Stack.REST,
      Stack.DOCKER,
      Stack.TRUFFLE,
      Stack.GANACHE,
      Stack.SOLIDITY,
      Stack.HARDHAT,
    ],
  },
  {
    title: "Full Stack Developer",
    date: "2019 – March 2022",
    company: "Terexov",
    description: [
      "Building react websites in a small team",
      "React projects configuration with webpack and babel",
      "Backend and frontend deployment",
      "Building backends with ExpressJS",
    ],
    place: "Saint Petersburg",
    stack: [
      Stack.TYPESCRIPT,
      Stack.GIT,
      Stack.JIRA,
      Stack.HTML,
      Stack.CSS,
      Stack.SASS,
      Stack.JS,
      Stack.STYLED_COMPONENTS,
      Stack.FRAMER_MOTION,
      Stack.REACT,
      Stack.REDUX,
      Stack.WEBPACK,
      Stack.BABEL,
      Stack.NODEJS,
      Stack.EXPRESS,
      Stack.MONGO,
      Stack.REST,
    ],
  },
];

// Stack.TYPESCRIPT,
// Stack.GIT,
// Stack.JIRA,
// Stack.HTML,
// Stack.CSS,
// Stack.SASS,
// Stack.JS,
// Stack.STYLED_COMPONENTS,
// Stack.FRAMER_MOTION,
// Stack.REACT,
// Stack.NEXTJS,
// Stack.REDUX,
// Stack.WEBPACK,
// Stack.BABEL,
// Stack.NODEJS,
// Stack.EXPRESS,
// Stack.NESTJS,
// Stack.MONGO,
// Stack.REDIS,
// Stack.MySQL,
// Stack.REST,
// Stack.GRAPH,
// Stack.STRAPI,
// Stack.WEBAPI,
// Stack.CSHARP,
// Stack.DOTNET,
// Stack.SWAGGER,
// Stack.JENKINS,
// Stack.RABBIT_MQ,
// Stack.GRPC,
// Stack.PROTO,
// Stack.MICROSERVICES,
// Stack.DOCKER,
// Stack.TRUFFLE,
// Stack.GANACHE,
// Stack.SOLIDITY,
